default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['USERNAME_DB'] %>
  password: <%= ENV['PASSWORD_DB'] %>

development:
  <<: *default
  database: ruby_tify_db

test:
  <<: *default
  database: ruby_tify_db_test

production:
  <<: *default
  database: ruby_tify_db_production
